baseURL      = "https://7ongxia.github.io/"
title        = "Jong Kim"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10

[params]
    dateform        = "Jan 2, 2006"
    dateformShort   = "Jan 2"
    dateformNum     = "2006-01-02"
    dateformNumTime = "2006-01-02 15:04"

    # Subtitle for home
    homeSubtitle = "it's a good life, if you don't weaken"

    # Set disableReadOtherPosts to true in order to hide the links to other posts.
    disableReadOtherPosts = false

    # Enable sharing buttons, if you like
    enableSharingButtons = false

    # Metadata mostly used in document's head
    description = "My Dev blog"
    keywords = "homepage, blog, dev"
    images = [""]

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
    [languages.en]
    title = "Jong Kim"
    # subtitle = "A simple theme for Hugo"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
        logoText = "$ cd /7ong/"
        logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

    # And you can even create generic menu
    
    [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"

    [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "/posts"

    [[menu.main]]
    identifier = "journal"
    name       = "Journal"
    url        = "/journals"

    [[params.social]]
    name = "email"
    url = "7ongxia@gmail.com"

    [[params.social]]
    name = "github"
    url = "https://github.com/7ongxia"
    
    [[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/jon-gha/"
    